spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: surveyApp
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

  datasource:
    url: jdbc:mysql://localhost:3306/survey_app
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: info
        org:
          hibernate: debug

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  access-token:
      expiration:
        mills: 1800000